/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CondicionantesRouteImport } from './routes/condicionantes'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as IaRouteImport } from './routes/ia'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as ProcessosRouteImport } from './routes/processos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicionantesRoute = CondicionantesRouteImport.update({
  id: '/condicionantes',
  path: '/condicionantes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/condicionantes': typeof CondicionantesRoute
  '/documentos': typeof DocumentosRoute
  '/ia': typeof IaRoute
  '/integracoes': typeof IntegracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/processos': typeof ProcessosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/condicionantes': typeof CondicionantesRoute
  '/documentos': typeof DocumentosRoute
  '/ia': typeof IaRoute
  '/integracoes': typeof IntegracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/processos': typeof ProcessosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/clientes': typeof ClientesRoute
  '/condicionantes': typeof CondicionantesRoute
  '/documentos': typeof DocumentosRoute
  '/ia': typeof IaRoute
  '/integracoes': typeof IntegracoesRoute
  '/pendencias': typeof PendenciasRoute
  '/processos': typeof ProcessosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/clientes'
    | '/condicionantes'
    | '/documentos'
    | '/ia'
    | '/integracoes'
    | '/pendencias'
    | '/processos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/clientes'
    | '/condicionantes'
    | '/documentos'
    | '/ia'
    | '/integracoes'
    | '/pendencias'
    | '/processos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendario'
    | '/clientes'
    | '/condicionantes'
    | '/documentos'
    | '/ia'
    | '/integracoes'
    | '/pendencias'
    | '/processos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  ClientesRoute: typeof ClientesRoute
  CondicionantesRoute: typeof CondicionantesRoute
  DocumentosRoute: typeof DocumentosRoute
  IaRoute: typeof IaRoute
  IntegracoesRoute: typeof IntegracoesRoute
  PendenciasRoute: typeof PendenciasRoute
  ProcessosRoute: typeof ProcessosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicionantes': {
      id: '/condicionantes'
      path: '/condicionantes'
      fullPath: '/condicionantes'
      preLoaderRoute: typeof CondicionantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  ClientesRoute: ClientesRoute,
  CondicionantesRoute: CondicionantesRoute,
  DocumentosRoute: DocumentosRoute,
  IaRoute: IaRoute,
  IntegracoesRoute: IntegracoesRoute,
  PendenciasRoute: PendenciasRoute,
  ProcessosRoute: ProcessosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
